### ISSUE TITLE
How do I get API token

### ISSUE THREAD

**Issue by 10williamsjoel** [YtoTech/libreview-data-export#1]
Hi @MonsieurV,
Does this still work for you, I was hoping to use something like this to automatically download my libreview CSV however I haven't been able to get this to work. How do you get the api token, I'm not sure if what I did was correct.
Thanks

**Comment by MonsieurV** [comment]
Hi @10williamsjoel,

I don't use it anymore. Prefer not to document more, as I'm not sure this goes with the ToS.

You may read that again:
> you can login and use your browser Web Developer Network panel to search for a Bearer token on Authorization request header to api.libreview.io.

(Look at the network panel; the Bearer token is what goes after `Bearer` - this would look like`Bearer <your yoken>` in the request headers)

Good luck.

**Comment by 10williamsjoel** [comment]
Hi  @MonsieurV <https://github.com/MonsieurV>,

Thank you for your reply, I have now been able to get this to work, I
appreciate you making this available, thank you very much!

Many thanks,

Joel
