### ISSUE TITLE
Requesting data export from API directly

### ISSUE THREAD

**Issue by jonassvalin** [YtoTech/libreview-data-export#7]
Hi!
I'm looking for a way of requesting historic glucose measurements programatically using LibreView (NOT LibreLinkUp). I've experimented with the /glucoseHistory endpoint and from my understanding the way that one works is that it gives you the average values (let's say, your value at 6:00 AM, averaged over for example 14 days), rather than the exact measurements. 

The CSV that you can download from the /export endpoint does give the exact measurements, but is only available behind a Google captcha, and so is difficult to access programatically. Have you found any other endpoints or ways of accessing the exact measurements? Thanks in advance!

**Comment by MonsieurV** [comment]
Hi @jonassvalin,

> Have you found any other endpoints or ways of accessing the exact measurements? Thanks in advance!

No, and I'm pretty sure this is not the Abbott policy to make that open to automation. Anyway, I'm not anymore into this project, not even having a reader to test, so I can't help more. I'll show the project as archived.

Good luck!
